name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * 0' # Run this workflow every Sunday at midnight

jobs:
  weekly-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main # Checkout the dev branch

      - name: Check for commits and pull requests
        id: check
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
            const commits = await github.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              since,
            });
            const pulls = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
            });
            const hasUpdates = commits.data.length > 0 || pulls.data.some(pull => new Date(pull.updated_at) >= new Date(since));
            return hasUpdates;
      
      - name: Date
        id: date
        run: |
          echo "today=$(date +%Y%m%d))" >> "$GITHUB_OUTPUT"

      - name: Create release
        if: steps.check.outputs.result == 'true'
        uses: comnoco/create-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-${{ steps.date.outputs.today }}
          release_name: Nightly release ${{ steps.date.outputs.today }}
          draft: false
          prerelease: true